Ensure tsx layout files will be loaded
I'd come across an issue my default layout file (`index.tsx`) wasn't being loaded. 

Here's my next config:
```
const withMDX = require("next-mdx-enhanced")({
  defaultLayout: true
});

module.exports = withMDX({});
```

And this was the error
```
Module not found: Can't resolve '~/next-site/layouts/index' in '~/next-site/pages/blog'

> Build error occurred
Error: > Build failed because of webpack errors
    at build (~/next-site/node_modules/next/dist/build/index.js:9:900)
```

Now, I have tsx files in my project that are otherwise working. Updating the import statement to point to the specific matched file fixes the issue though.